encyclopedia/urls.py
from django.urls import path

from . import views
app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="home"),
    path("contribute/", views.contribute, name="contribute"),
    path("wiki/<str:title>/", views.entry, name="entry"),
    path("wiki/<str:title>/edit/", views.edit, name="edit"),
    path("error/", views.error, name="error"),
    path("search_results/", views.search_results, name="search_results"),
    path("<str:catch>/", views.error, name="catch")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

encyclopedia/views.py
from django.shortcuts import render
from . import util
from markdown2 import markdown_path
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
import random


class NewEntryForm(forms.Form):
    """
    Form For Adding New entries. Takes a title and description field.
    """
    title = forms.CharField(label="Enter Title")
    description = forms.CharField(label="Enter Description", widget=forms.Textarea)


class EditForm(forms.Form):
    """
    Form for editing entries. Only Descriptions are editable.
    """
    description = forms.CharField(widget=forms.Textarea)


"""
 rand_list = random.choice(util.list_entries())
 
Stores a random entry to redirect the user to if the 
random button is clicked. Had to be accessible from 
every instance of,  render(request, URL), as template URL tags 
were not able to take arguments as I was expecting.
Refactoring needed.
"""


def index(request):
    rand_list = random.choice(util.list_entries())
    """
    View function For landing page. Links to home.html.
    Displays all current entries.
    """
    request.session["entries"] = util.list_entries()
    return render(request, "encyclopedia/home.html", {
        "entries": request.session["entries"],
        "random": rand_list
    })


def entry(request, title):
    rand_list = random.choice(util.list_entries())
    """
    If a url for an entry DNE, returns an error page.
    Else, it returns the entry populated with the markdown title and
    description.
    """
    if util.get_entry(title) is None:
        return render(request, "encyclopedia/error.html", {'title': title, 'random': rand_list})
    entry_formatted = markdown_path('media/entries/' + title + '.md', extras=["break-on-newline"])
    return render(request, "encyclopedia/entry.html", {
        'entry': entry_formatted,
        'title': title,
        "random": rand_list
    })


def contribute(request):
    rand_list = random.choice(util.list_entries())
    """
    If method == POST, checks if entry already exist & displays warning, 
    if not, it adds entry to /entries/ and redirects to the home page
    """
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            form_title = form.cleaned_data["title"].lower()
            check_list = util.list_entries()
            check_list_low = [x.lower() for x in check_list]
            for title in check_list_low:
                if form_title == title:
                    error = "Entry Already Exist!"
                    return render(request, "encyclopedia/contribute.html", {"form": form,
                                                                            "error": error,
                                                                            "random": rand_list})
            description = form.cleaned_data["description"]
            title = form.cleaned_data["title"]
            description_formatted = '#' + title.title() + '\n' + description.capitalize()
            request.session['new_entry'] = util.save_entry(title, description_formatted)
            request.session["entries"].append(request.session['new_entry'])
            return HttpResponseRedirect(reverse("encyclopedia:home"))
        else:
            return render(request, "encyclopedia/contribute.html", {
                "form": form
            })
    """
    If method == GET, returns a blank form to add a new entry.
    """
    return render(request, "encyclopedia/contribute.html", {
            'form': NewEntryForm(),
            "random": rand_list
            })


def edit(request, title):
    rand_list = random.choice(util.list_entries())
    """
    If method == Post, it updates the entries' description
    """
    if request.method == "POST":
        form = EditForm(request.POST)
        if form.is_valid():
            description = form.cleaned_data["description"]
            title_2 = title
            description_formatted = '#' + title_2.title() + '\n' + description.capitalize()
            util.save_entry(title_2, description_formatted)
            return HttpResponseRedirect("/wiki/" + title_2)
        else:
            return render(request, "encyclopedia/contribute.html", {"form": form})
    """
    If method == Get, it populates the form with
    the existing description for each entry
     """
    pre_populate = util.get_entry(title)
    pre_populate = pre_populate.replace(("#" + title), "", 1)
    f = EditForm(initial={'description': pre_populate})

    return render(request, "encyclopedia/edit.html", {
        'title': title,
        'form': f,
        'random': rand_list
    })


def error(request, catch):
    """
    Displays error page. Will catch entries that DNE if they are accessed
    from the url directly.
    """
    rand_list = random.choice(util.list_entries())
    return render(request, "encyclopedia/error.html", {
        "catch": catch,
        "random": rand_list
    })


def search_results(request):
    """
    Takes input from user, and runs a search through all
    existing entries to identify if the search is a sub-string
    of any entries. Will return all entries in which the input
    is a sub string. If the Input is an exact match for an entry, it redirects straight
    to the url for that entry. If the input is a sub string of no entries
    it returns a DNE warning.
    """
    rand_list = random.choice(util.list_entries())
    if request.method == 'POST':
        all_entries = util.list_entries()
        converted_entries = [x.lower() for x in all_entries]
        query_entries = []
        search_query = request.POST.get("q").lower()
        for x in all_entries:
            if search_query == x.lower():
                return HttpResponseRedirect("/wiki/" + search_query.capitalize() + "/")
        for entry in converted_entries:
            if search_query in entry:
                query_entries.append(entry)
        titles = [x.capitalize() for x in query_entries]
        return render(request, "encyclopedia/search_results.html", {
            'entries': titles,
            'query': search_query.capitalize(),
            "random": rand_list
        })

encyclopedia/templates/encyclopedia/contribute.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
    <div>
    <h1>Contribute Content to Help Keep Program-Wiki Up to Date!</h1>
        <form action="{% url 'encyclopedia:contribute' %}" method="post">
            {% csrf_token %}
            <div class="add-entry">
                {{ form }}
            </div>
            <input type="submit">
        </form>
        <h1 style="color: red;">{{ error }}</h1>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
    <h3>Edit Content for:</h3>
    <h1>{{ title }}</h1>
     <form action="/wiki/{{ title }}/edit/" method="post">
            {% csrf_token %}
            <div class="add-entry" id="edit">
                {{ form }}
            </div>
            <input type="submit">
        </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title | safe }}
{% endblock %}

{% block body %}
    <div class="testtest">
        <h1>{{ entry |safe }}</h1>
        <a href="/wiki/{{ title }}/edit/">
            <button type="submit" class="edit-button">Edit</button>
        </a>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
    <div class="error-404">
        <h1>Error 404</h1>
        {% if title %}
            <h1>Entry "{{ title }}" Does Not Exist</h1>
        {% else %}
            <h1>Path "/{{ catch }}/" Does Not Exist</h1>
        {% endif %}
    </div>
{%  endblock %}

encyclopedia/templates/encyclopedia/home.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    <div class="rcolm">
            <ul>
                {% for entry in entries %}
                    <div class="testing">
                        <li>
                            <a href="/wiki/{{ entry }}/">{{ entry }}</a>
                        </li>
                    </div>
                {% endfor %}
            </ul>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/css/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Program-Wiki</h2>
                <form action="{% url "encyclopedia:search_results" %}", method="post">
                    {% csrf_token %}
                    <input type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:home' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:entry' random  %}">
                        Random Page
                    </a>
                </div>
                <div>
                    <a href="{% url "encyclopedia:contribute" %}">
                    Contribute Content
                    </a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
         <h1>Search Results for "{{ query }}"</h1>
    <hr>
    {% if entries %}
        <div class="rcolm">
                <ul>
                    {% for entry in entries %}
                        <div class="testing">
                            <li>
                                <a href="/wiki/{{ entry }}/">{{ entry }}</a>
                            </li>
                        </div>
                    {% endfor %}
                </ul>
        </div>
    {% else %}
        <h1>No entries matching your search were found...</h1>
    {% endif %}
{% endblock %}